[tool.black]
skip-string-normalization=true
skip-magic-trailing-comma=false
line-length=89

[tool.flake8]
ignore=['WPS100', 'WPS226', 'WPS305', 'WPS317', 'WPS348', 'W503', 'D100', 'D101', 'D102', 'D103', 'D104', 'D105', 'D106']
per-file-ignores = [
    '*/commands/*.py:WPS110,WPS436',
    'admin.py:WPS110',
    'apps.py:F401,WPS301,WPS433',
    'models.py:WPS306',
    'R4C/robots/utils.py:WPS210',
    'R4C/robots/views.py:WPS515',
    'serializers.py:WPS110',
    'settings.py:WPS407',
    'urls.py:WPS433',
]
exclude=['*/migrations/*.py', 'manage.py']
max-cognitive-complexity=10
max-line-length=89
class_attributes_order=['field', 'meta_class', 'nested_class', 'magic_method', 'property_method', 'static_method', 'class_method', 'method', 'private_method']

[tool.isort]
known_first_party=['api', 'customers', 'orders', 'robots']
profile='black'

[tool.mypy]
exclude=['migrations']
ignore_missing_imports=true

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "R4C.settings"
filterwarnings = [
    'ignore::DeprecationWarning'
]
python_paths = '.'
norecursedirs = ['venv/*']
addopts = '-vv -p no:cacheprovider'
testpaths = ['tests/']
python_files = ['test_*.py']
