# Generated by Django 4.1.5 on 2023-01-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_serial', models.CharField(help_text="Robot's serial number", max_length=5, verbose_name='robot_serial')),
                ('customer', models.ForeignKey(help_text='Order customer', on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-pk',),
            },
        ),
    ]
