# Generated by Django 4.2.5 on 2023-09-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('robots', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'customer',
                    models.ForeignKey(
                        help_text='Order customer',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orders',
                        to='customers.customer',
                        verbose_name='customer',
                    ),
                ),
                (
                    'robot_assigned',
                    models.OneToOneField(
                        blank=True,
                        help_text='Robot assigned to this order',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='order',
                        to='robots.robot',
                        verbose_name='robot_assigned',
                    ),
                ),
                (
                    'robot_version',
                    models.ForeignKey(
                        help_text='Version of ordered robot',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='orders',
                        to='robots.robotversion',
                        verbose_name='robot',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-pk',),
            },
        ),
    ]
