# Generated by Django 4.1.5 on 2023-01-29 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='robot_serial',
        ),
        migrations.AddField(
            model_name='order',
            name='robot',
            field=models.ForeignKey(default=1, help_text='Version of ordered robot', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='robots.robotversion', verbose_name='robot'),
            preserve_default=False,
        ),
    ]
