# Generated by Django 4.1.5 on 2023-01-30 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
        ('orders', '0003_alter_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='robot',
            new_name='robot_version',
        ),
        migrations.AddField(
            model_name='order',
            name='robot_assigned',
            field=models.OneToOneField(help_text='Robot assigned to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='robots.robot', verbose_name='robot_assigned'),
        ),
    ]
