# Generated by Django 4.1.5 on 2023-01-30 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
        ('orders', '0004_rename_robot_order_robot_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='robot_assigned',
            field=models.OneToOneField(blank=True, help_text='Robot assigned to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='robots.robot', verbose_name='robot_assigned'),
        ),
    ]
