# Generated by Django 4.2.5 on 2023-09-26 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'model',
                    models.SlugField(
                        help_text='Robot model',
                        max_length=2,
                        unique=True,
                        verbose_name='model',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Robot Model',
                'verbose_name_plural': 'Robot Models',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='RobotVersion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'version',
                    models.SlugField(
                        help_text='Robot model version',
                        max_length=2,
                        verbose_name='version',
                    ),
                ),
                (
                    'model',
                    models.ForeignKey(
                        help_text='Robot model',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='versions',
                        to='robots.robotmodel',
                        verbose_name='model',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Robot Version',
                'verbose_name_plural': 'Robot Versions',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        help_text='Robot creation date and time', verbose_name='created'
                    ),
                ),
                (
                    'version',
                    models.ForeignKey(
                        help_text='Robot version',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='robots',
                        to='robots.robotversion',
                        verbose_name='version',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Robot',
                'verbose_name_plural': 'Robots',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='robotversion',
            constraint=models.UniqueConstraint(
                fields=('model', 'version'), name='model_version_unique_constraint'
            ),
        ),
    ]
