# Generated by Django 4.2.5 on 2023-09-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='version',
            field=models.ForeignKey(
                help_text='Robot version',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='robots',
                to='robots.robotversion',
                verbose_name='version',
            ),
        ),
    ]
